// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
 // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXAQfbzCoZlMWVQ89a99MY6Yia1Q0hib4',
    appId: '1:129746857472:web:18e230c9aadb950c4f72e5',
    messagingSenderId: '129746857472',
    projectId: 'wellcomrea-ffbe5',
    authDomain: 'wellcomrea-ffbe5.firebaseapp.com',
    storageBucket: 'wellcomrea-ffbe5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnTEWT8E6Yw5UF6Ln1zJyI9F8AZohehc4',
    appId: '1:129746857472:android:879a2bbffb99ed484f72e5',
    messagingSenderId: '129746857472',
    projectId: 'wellcomrea-ffbe5',
    storageBucket: 'wellcomrea-ffbe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkgb8_azNMVXh23hFinHohy7zO4Z7i9eA',
    appId: '1:129746857472:ios:53eee17bfb0a96584f72e5',
    messagingSenderId: '129746857472',
    projectId: 'wellcomrea-ffbe5',
    storageBucket: 'wellcomrea-ffbe5.appspot.com',
    iosBundleId: 'com.example.wellComRea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkgb8_azNMVXh23hFinHohy7zO4Z7i9eA',
    appId: '1:129746857472:ios:53eee17bfb0a96584f72e5',
    messagingSenderId: '129746857472',
    projectId: 'wellcomrea-ffbe5',
    storageBucket: 'wellcomrea-ffbe5.appspot.com',
    iosBundleId: 'com.example.wellComRea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXAQfbzCoZlMWVQ89a99MY6Yia1Q0hib4',
    appId: '1:129746857472:web:25cd2fe5eee770ca4f72e5',
    messagingSenderId: '129746857472',
    projectId: 'wellcomrea-ffbe5',
    authDomain: 'wellcomrea-ffbe5.firebaseapp.com',
    storageBucket: 'wellcomrea-ffbe5.appspot.com',
  );

}